# Prompt wide options
format = """
|$directory
|$username@$hostname$fill$time
|($git_status)($git_state)($git_branch$git_commit$git_metrics)$fill($nodejs)(|$golang)(|$rust)(|$python)(|$c)(|$cpp)
â£$character
"""

palette = 'panda'

[palettes.panda]
pink = '#FF13F0'

[username]
format = '[$user]($style)'
disabled=false
show_always=true

[hostname]
ssh_only = false
ssh_symbol = 'ğŸ•¹ï¸'
format='[$hostname](green bold italic) [$ssh_symbol](bold)'

[git_branch]
symbol = 'ğŸŒ¿'
truncation_symbol = '...'
format = 'on [$symbol $branch(:%remote_branch)](bold) '

[git_commit]
commit_hash_length=8
format='on commit [\($hash$tag\)](bold) '
only_detached=false
tag_disabled=false
tag_symbol='ğŸ“Œ'

[git_state]
rebase = 'ğŸ› ï¸'
merge = 'ğŸ§¬'
revert = 'â†º'
cherry_pick = 'ğŸ’'
bisect = 'âŒ‡'
am = 'âœ‰ï¸'
am_or_rebase = 'âœ‰ï¸/ğŸ› ï¸'
style = ''

[git_metrics]
disabled=false

[git_status]
disabled=false
ignore_submodules=true
conflicted='âš”ï¸'
ahead='â†ª'
behind='â†©'
diverged='ğŸ”—'
up_to_date='âœ…'
untracked='âŒ'
stashed='ğŸ•‹'
modified='âœï¸'
staged='ğŸŸï¸'
renamed='ğŸ”§'
deleted='ğŸ—‘ï¸'
typechanged=''

[golang]
symbol='ğŸ¦« '
format='[$symbol($version)]($style)'
version_format='v${major}.${minor}'
disabled=false

[rust]
symbol='ğŸ¦€ '
format='[$symbol($version)]($style)'
version_format='v${major}.${minor}'
disabled=false

[python]
symbol='ğŸ '
format='[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format='v${major}.${minor}'
disabled=false

[nodejs]
format='[$symbol($version )]($style)'
version_format='v${major}.${minor}'
disabled=false

[c]
symbol='ğŸ‡¨ '
format='[$symbol($version(-$name)]($style)'
version_format='v${major}.${minor}'
disabled=false

[cpp]
symbol='âœ™ '
format='[$symbol($version(-$name)]($style)'
version_format='v${major}.${minor}'
disabled=false

[time]
format='[$time](bold green)'
time_format='%Y-%m-%d %H:%M:%S.%3f'
disabled=false

[fill]
disabled=false
symbol=' '

[directory]
truncation_symbol='.../'
